# Generated by Django 5.0 on 2025-02-03 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_contactperson_contactpersonsocialmedia_sitesettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactperson',
            name='social_medias',
        ),
        migrations.RemoveField(
            model_name='sitesettingssocialmedia',
            name='site_settings',
        ),
        migrations.RemoveField(
            model_name='sitesettingssocialmedia',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='social_medias',
        ),
        migrations.AlterModelOptions(
            name='contactperson',
            options={'verbose_name': 'Kontakt persona', 'verbose_name_plural': 'Kontakt personalari'},
        ),
        migrations.CreateModel(
            name='SocialMediaPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('icon', models.CharField(help_text='Ikonka nomini https://fontawesome.com/v6/search?ic=free dan oling, misol uchun: fab fa-telegram', max_length=200, verbose_name='Ikonka')),
                ('link', models.URLField(verbose_name='Havola')),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.contactperson')),
            ],
            options={
                'verbose_name': 'Ijtimoiy tarmoqlar',
                'verbose_name_plural': 'Ijtimoiy tarmoqlar',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('icon', models.CharField(help_text='Ikonka nomini https://fontawesome.com/v6/search?ic=free dan oling, misol uchun: fab fa-telegram', max_length=200, verbose_name='Ikonka')),
                ('link', models.URLField(verbose_name='Havola')),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.sitesettings')),
            ],
            options={
                'verbose_name': 'Ijtimoiy tarmoqlar',
                'verbose_name_plural': 'Ijtimoiy tarmoqlar',
            },
        ),
        migrations.DeleteModel(
            name='ContactPersonSocialMedia',
        ),
        migrations.DeleteModel(
            name='SiteSettingsSocialMedia',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
