# Generated by Django 5.0 on 2025-02-07 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_contactperson_social_medias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaperson',
            name='contact_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='web.contactperson'),
        ),
        migrations.AlterField(
            model_name='socialmediasite',
            name='icon',
            field=models.CharField(default='fa-brands fa-telegram', help_text="Ikonka nomini <a href='https://fontawesome.com/v6/search?ic=free'>BU YERDAN</a> dan oling, misol uchun: fab fa-telegram", max_length=200, verbose_name='Ikonka'),
        ),
        migrations.AlterField(
            model_name='socialmediasite',
            name='site_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='web.sitesettings'),
        ),
    ]
