# Generated by Django 5.0 on 2025-02-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_socialmediaperson_contact_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaperson',
            name='name',
        ),
        migrations.RemoveField(
            model_name='socialmediasite',
            name='name',
        ),
        migrations.AlterField(
            model_name='socialmediaperson',
            name='icon',
            field=models.CharField(help_text='fa-brands fa-telegram', max_length=200, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='socialmediaperson',
            name='link',
            field=models.CharField(max_length=500, verbose_name='Havola'),
        ),
        migrations.AlterField(
            model_name='socialmediasite',
            name='icon',
            field=models.CharField(help_text='fa-brands fa-telegram', max_length=200, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='socialmediasite',
            name='link',
            field=models.CharField(max_length=500, verbose_name='Havola'),
        ),
    ]
