# Generated by Django 5.0 on 2025-02-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_team_description_en_team_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamsocialmedia',
            options={'verbose_name': 'Ijtimoiy tarmoqlar', 'verbose_name_plural': 'Ijtimoiy tarmoqlar'},
        ),
        migrations.AddField(
            model_name='teamsocialmedia',
            name='icon',
            field=models.CharField(default='', help_text='fa-brands fa-telegram', max_length=200, verbose_name='Nomi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamsocialmedia',
            name='link',
            field=models.CharField(default='', max_length=500, verbose_name='Havola'),
            preserve_default=False,
        ),
    ]
