# Generated by Django 5.0 on 2025-02-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_teamsocialmedia_options_teamsocialmedia_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='lat_long',
            field=models.CharField(blank=True, help_text='Masalan: 41.311081, 69.289632', max_length=200, null=True, verbose_name='Xarita koordinatalari'),
        ),
    ]
