# Generated by Django 5.0 on 2025-02-09 12:49

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_contactperson_full_name_sitesettings_lat_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_us',
            field=tinymce.models.HTMLField(default=1, verbose_name='Biz haqimizda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_us_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Biz haqimizda'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_us_ru',
            field=tinymce.models.HTMLField(null=True, verbose_name='Biz haqimizda'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_us_uz',
            field=tinymce.models.HTMLField(null=True, verbose_name='Biz haqimizda'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='lat_long',
            field=models.CharField(blank=True, help_text='Masalan: 41.311081, 69.289632', max_length=200, null=True, verbose_name='Xaritadagi koordinatalar'),
        ),
    ]
