# Generated by Django 5.0 on 2025-02-09 17:19

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_licenseachievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/service/%Y/%m/%d/', verbose_name='Fon rasmi')),
                ('icon', models.ImageField(upload_to='uploads/service/%Y/%m/%d/', verbose_name='Ikonka rasmi')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Sarlavha')),
                ('slug', models.SlugField(default='', unique=True, verbose_name='Qisqa link')),
                ('content', tinymce.models.HTMLField(verbose_name='Matn')),
                ('content_uz', tinymce.models.HTMLField(null=True, verbose_name='Matn')),
                ('content_ru', tinymce.models.HTMLField(null=True, verbose_name='Matn')),
                ('content_en', tinymce.models.HTMLField(null=True, verbose_name='Matn')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
            },
        ),
        migrations.AlterModelOptions(
            name='licenseachievement',
            options={'verbose_name': 'Litsensiya va yutuqlar', 'verbose_name_plural': 'Litsensiya va yutuqlar'},
        ),
    ]
