# Generated by Django 5.0 on 2025-02-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_event_active_event_created_at_event_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/event_images/%Y/%m/%d/', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': 'Tadbir lavhalari',
                'verbose_name_plural': 'Tadbir lavhalari',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/gallery/%Y/%m/%d/', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': 'Galereya',
                'verbose_name_plural': 'Galereya',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/partner/%Y/%m/%d/', verbose_name='Rasm')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Tadbir', 'verbose_name_plural': 'Tadbirlar'},
        ),
    ]
